name: Tests
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

  install-example-deps:
    needs: checkout
    runs-on: ubuntu-20.04
    steps:
      - name: Cache example dependencies
        id: example-cache
        uses: actions/cache@v2
        with:
          path: example/node_modules
          key: example-modules-${{ hashFiles('example/package-lock.json') }}
      - name: Install example dependencies
        if: steps.example-cache.outputs.cache-hit != 'true'
        run: cd example; npm ci --ignore-scripts

  install-root-deps:
    needs: checkout
    runs-on: ubuntu-20.04
    steps:
      - name: Cache root dependencies
        id: root-cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install root dependencies
        if: steps.root-cache.outputs.cache-hit != 'true'
        run: cd example; npm ci --ignore-scripts

  unit-tests:
    needs: install-root-deps
    runs-on: ubuntu-latest
    steps:
      - run: npm run test

  cypress-run:
    needs: [install-root-deps, install-example-deps]
    runs-on: ubuntu-20.04
    steps:
      - name: Build project
        run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm run start-example
          wait-on: 'http://localhost:3000'
